config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "posts#index"
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :facebook_posts, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

  # after_create :publish_to_facebook

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?

  def sign_out_user
    sign_out(current_user)
    redirect_to root_path, notice: 'You have been signed out successfully.'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to @post, notice: 'Коментар успішно додано.'
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post, notice: 'Коментар успішно видалено.'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/facebook_posts_controller.rb
class FacebookPostsController < ApplicationController
  def create
    post_id = params[:post][:id]
    post = Post.find(post_id)

    user = Koala::Facebook::API.new(ENV['FACEBOOK_ACCESS_TOKEN'])

    message = "Новий пост на блозі: #{post.title}\n#{post.body}"

    options = { 'link' => post_url(post) }

    user.put_wall_post(message, options)

    redirect_to post, notice: 'Повідомлення успішно опубліковано на Facebook.'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Пост успішно створено.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Пост успішно оновлено.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Пост успішно видалено.'
  end

  # def publish_to_facebook
  #   user = Koala::Facebook::API.new(ENV['FACEBOOK_ACCESS_TOKEN'])

  #   message = "Новий пост на блозі: #{@post.title}"

  #   options = { 'link' => post_url(@post), 'picture' => @post.image.url(:thumb) }

  #   user.put_wall_post(message, options)

  #   redirect_to @post, notice: 'Повідомлення успішно опубліковано на Facebook.'
  # end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
  def destroy
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/facebook_posts_helper.rb
module FacebookPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [post, comment] do |f| %>
 <p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
  <%= f.submit 'Додати коментар' %>
<% end %>

app/views/facebook_posts/_form.html.erb
<%= form_for(@post, url: facebook_posts_path, method: :post) do |f| %>
  <%= f.hidden_field :id, value: @post.id %>
  <%= f.submit 'Опублікувати на Facebook', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloging</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
 <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.label :image %>
  <%= f.file_field :image %>
</p>
  <%= f.submit 'Зберегти' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %>!</p>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

<h1>Список постів</h1>

<%= link_to 'Новий пост', new_post_path %>
 <div class="post">
<% @posts.each do |post| %>
 
    <h2><%= link_to post.title, post %></h2>
    <p><%= truncate(strip_tags(post.body), length: 100) %></p>
    <div class = buttons>
   <b class = "button"> <%= link_to 'Показати', post %>   </b>
      <b class = "button"> <%= link_to 'Редагувати', edit_post_path(post) %>   </b>
     <b class = "button">  <%= link_to 'Видалити', post, method: :delete, data: { confirm: 'Ви впевнені?' } %>   </b>
     <div>
  
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2 class="blog-title"><%= @post.title %></h2>
<p class="post"><%= @post.body %></p>
<p>
<%= image_tag @post.image.url(:thumb) if @post.image.present? %>
</p>
<div class = "buttons">
<b class = "button"><%= link_to "Edit", edit_post_path(@post) %>  </b>
<b class = "button">  <%= link_to "Destroy", post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></b>
</div>
<b class = "button"><%= link_to 'Back', posts_path %></b>
<%= render 'facebook_posts/form', post: @post %>
<%= render 'comments/form', post: @post, comment: @comment %>

<% @post.comments.each do |comment| %>
  <p><%= comment.body %></p>
 <p class = "button">
    <%= link_to "Destroy Comment", [comment.post, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>